version: '3'
services:
  eureka:
    container_name: eureka
    build:
      context: eureka
      args:
      - artifact_id=eureka
      - version=0.0.1-SNAPSHOT
  zuul:
    container_name: zuul
    build:
      context: zuul
      args:
      - artifact_id=zuul
      - version=0.0.1-SNAPSHOT
    depends_on:
    - eureka
  mysql:
    container_name: mysql
    image: mysql
  user-creation-api:
    container_name: user-creation-api
    build:
      context: user-creation-api
      args:
      - artifact_id=user-creation-api
      - version=0.0.1-SNAPSHOT
    depends_on:
    - zuul
    - mysql
  cv-api-for-cloud:
    container_name: cv-api-for-cloud
    build:
      context: cv-api-for-cloud
      args:
      - artifact_id=cv-api
      - version=0.0.1-SNAPSHOT
    depends_on:
    - zuul
    - mysql
  front-end:
    container_name: front-end
    build:
      context: front-end
      args:
      - artifact_id=front-end
      - version=0.0.1-SNAPSHOT
    depends_on:
    - cv-api-for-cloud
    - user-creation-api
    ports:
    - "80:3000"
  activemq:
    container_name: activemq
    image: activemq
  mongodb:
    container_name: mongodb
    image: mongo
  consumer:
    container_name: consumer
    build:
      context: consumer
      args:
      - artifact_id=consumer
      - version=0.0.1-SNAPSHOT
    depends_on:
    - activemq
    - mongodb
    - front-end
